APP_STL := gnustl_static
APP_CPPFLAGS := -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DCOCOS2D_DEBUG=1 -std=c++11 -fsigned-char

APP_ABI :=armeabi
APP_OPTIM := debug
APP_PLATFORM := android-9

NDK_TOOLCHAIN_VERSION=4.8
